x-extra_hosts: &extra_hosts
  - "ip100.local:192.168.0.100"
  - "ip101.local:192.168.0.101"
  - "ip102.local:192.168.0.102"
  - "ip103.local:192.168.0.103"
  - "ip104.local:192.168.0.104"
  - "ip105.local:192.168.0.105"
  - "ip106.local:192.168.0.106"
  - "ip107.local:192.168.0.107"
  - "ip108.local:192.168.0.108"
  - "ip109.local:192.168.0.109"
  - "ip110.local:192.168.0.110"
x-tz: &tz TZ=Asia/Shanghai
# x-tz: &tz TZ=America/New_York
services:
  php:
    hostname: php
    # build:
    #   context: ./Dockerfiles/php
    #   dockerfile: php.dockerfile
    image: ghini/php-think-swoole
    environment:
      - *tz
    volumes:
      - ./wwwroot:/wwwroot
      - ./etc/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - backend
    extra_hosts: *extra_hosts
    
  nginx:
    hostname: nginx
    image: nginx
    environment:
      - *tz
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./wwwroot:/wwwroot
      - ./etc/nginx/ssl:/etc/nginx/ssl
      - ./etc/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - backend
    
  mysql:
    hostname: mysql
    image: mysql
    environment:
      - *tz
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypassword
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - backend

  redis:
    hostname: redis
    image: redis
    environment:
      - *tz
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - backend
    command: ["redis-server", "--appendonly", "yes", "--appendfsync", "everysec"] # AOF操作持久化
    # command: ["redis-server", "--save", "900 1", "--save", "300 10", "--save", "60 10000"] # RDB快照持久化

  clickhouse:
    hostname: clickhouse
    image: clickhouse/clickhouse-server
    environment:
      - *tz
    ports:
      - 8123:8123
      - 9000:9000
      - 9181:9181
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      # - ./etc/clickhouse/default/config.xml:/etc/clickhouse-server/config.xml
      - ./etc/clickhouse/config.cluster.xml:/etc/clickhouse-server/config.xml 
      - ./etc/clickhouse/users.xml:/etc/clickhouse-server/users.xml
      - ./etc/clickhouse/keeper_config1.xml:/etc/clickhouse-keeper/keeper_config.xml
    networks:
      - backend
    extra_hosts: *extra_hosts

  elasticsearch:
    hostname: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:${ES_VERSION}
    environment:
      - *tz
      - discovery.type=single-node
      - ELASTIC_PASSWORD=changeme
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    networks:
      - backend
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - ./etc/elasticsearch/plugins:/usr/share/elasticsearch/plugins
  kibana:
    hostname: kibana
    image: docker.elastic.co/kibana/kibana:${ES_VERSION}
    environment:
      - *tz
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=changeme
    volumes:
      - ./etc/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    networks:
      - backend
  filebeat:
    hostname: filebeat
    image: docker.elastic.co/beats/filebeat:${ES_VERSION}
    environment:
      - *tz
    user: root
    command: ["filebeat", "-e", "--strict.perms=false"]
    volumes:
      - ./etc/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./etc/filebeat/test.log:/home/test.log
    depends_on:
      - elasticsearch
    networks:
      - backend
  logstash:
    hostname: logstash
    image: docker.elastic.co/logstash/logstash:${ES_VERSION}
    environment:
      - *tz
    volumes:
      - ./etc/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    ports:
      - "5044:5044"
    networks:
      - backend
    depends_on:
      - elasticsearch
  kafka:
    hostname: kafka
    image: apache/kafka
    environment:
      TZ: Asia/Shanghai
    volumes:
      - kafka_data:/kafka/data
      - ./etc/kafka/server.properties:/etc/kafka/docker/server.properties
    ports:
      - "9092:9092"
      - "9093:9093"
    networks:
      - backend

networks:
  backend:
  frontend:

volumes:
  mysql_data:
  clickhouse_data:
  redis_data:
  esdata:
  kafka_data:

