services:
  php:
    build:
      context: ./Dockerfiles/php
      dockerfile: php.dockerfile
    volumes:
      - ./wwwroot:/wwwroot
      - ./etc/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - backend
  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./wwwroot:/wwwroot
      - ./etc/nginx/ssl:/etc/nginx/ssl
      - ./etc/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php
    networks:
      - backend
    environment:
      - TZ=Asia/Shanghai
  mysql:
    image: mysql
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - backend

  redis:
    image: redis
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - backend
    command: ["redis-server", "--appendonly", "yes", "--appendfsync", "everysec"] # AOF操作持久化
    # command: ["redis-server", "--save", "900 1", "--save", "300 10", "--save", "60 10000"] # RDB快照持久化

  clickhouse:
    image: clickhouse/clickhouse-server
    ports:
      - 8123:8123
      - 9000:9000
      - 9009:9009
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    networks:
      - backend
  # clickhouse:
  #   build:
  #     context: ./Dockerfiles/clickhouse
  #     dockerfile: clickhouse.dockerfile
  #   volumes:
  #     - clickhouse_data:/var/lib/clickhouse
  #     - ./etc/clickhouse/config.xml:/etc/clickhouse-server/config.xml
  #   networks:
  #     - backend
  #   ports:
  #     - "8123:8123"
  #     - "9000:9000"
  #     - "9009:9009"
  #   environment:
  #     - TZ=Asia/Shanghai

  # kafka:
  #   image: wurstmeister/kafka
  #   ports:
  #     - "9092:9092"
  #   environment:
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
  #     KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #   # volumes:
  #   #   - ./etc/kafka:/etc/kafka # 挂载自定义的 kafka 配置
  #   depends_on:
  #     - zookeeper
  #   networks:
  #     - backend

  # zookeeper:
  #   image: wurstmeister/zookeeper
  #   ports:
  #     - "2181:2181"
  #   networks:
  #     - backend

  # rabbitmq:
  #   image: rabbitmq:management
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"
  #   networks:
  #     - backend

networks:
  backend:
  frontend:

volumes:
  mysql_data:
  clickhouse_data:
  redis_data: