input {
  beats {
    port => 5044
    add_field => { "[@metadata][source]" => "filebeat" }
  }
  kafka {
    bootstrap_servers => "kafka:9092"
    topics => ["my-topic"]
    auto_offset_reset => "earliest"  # 没有初始偏移量或者偏移量超出范围时，从最早的偏移量开始消费
    add_field => { "[@metadata][source]" => "kafka" }
  }
}

filter {
  mutate {
    remove_field => ["@version", "event", "tags"]
  }
  ruby {
    code => "
      require 'time'
      event.set('[@metadata][cn_date]', Time.now.getlocal('+08:00').strftime('%Y.%m.%d'))
    "
  }
}

output {
  # stdout {codec=>rubydebug}
  if [@metadata][source] == "filebeat" {
    elasticsearch {
      hosts => ["elasticsearch:9200"]
      index => "filebeat-logstash-%{[@metadata][cn_date]}"
    }
  }
  else if [@metadata][source] == "kafka" {
    elasticsearch {
      hosts => ["elasticsearch:9200"]
      index => "kafka-logstash-%{[@metadata][cn_date]}"
    }
  }
}
