version: '3'
services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
    - 8888:80
    volumes:
    - /home/www/:/usr/share/nginx/html
  php:
    image: myphp
    container_name: php
    volumes:
    - /home/www/:/usr/share/nginx/html
  mysql:
    image: mysql
    container_name: mysql
    environment:
    - MYSQL_ROOT_PASSWORD=password
