services:
  php:
    build:
      context: Dockerfiles/php
      dockerfile: php83
    volumes:
      - ./wwwroot:/wwwroot
      - ./etc/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - backend
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./wwwroot:/wwwroot
      - ./etc/nginx/ssl:/etc/nginx/ssl
      - ./etc/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php
    networks:
      - backend
    environment:
      - "TZ=Asia/Shanghai"
  mysql:
    image: mysql:8.0
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mydb
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - backend

  redis:
    image: redis
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - backend
    command: ["redis-server", "--appendonly", "yes", "--appendfsync", "everysec"] # AOF操作持久化
    # command: ["redis-server", "--save", "900 1", "--save", "300 10", "--save", "60 10000"] # RDB快照持久化


networks:
  backend:
  frontend:

volumes:
  mysql_data:
  clickhouse_data:
  redis_data: