filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml #/usr/share/filebeat/modules.d/*.yml
    reload.enabled: false

filebeat.inputs:
  - type: log
    paths:
      - /home/*.log
    
processors:
  - drop_fields:
      # tags @xxx event后面默认加上，去不掉
      fields: ["ecs","host","agent","log.offset","input"]

# output.logstash:
#   hosts: ["logstash:5044"]
output.elasticsearch:
  hosts: ["elasticsearch:9200"]


logging.level: error  # error, info 或 debug
