filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.inputs:
  - type: log
    paths:
      - /home/*.log
  - type: container
    paths:
      - /var/lib/docker/containers/*/*.log

processors:
  - add_fields:
      target: '@metadata'
      fields:
        beat: 'filebeat'
        version: '8.14.1'

# output.elasticsearch:
#   hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'
output.logstash:
  hosts: ["logstash:5044"]

# setup.kibana:
#   host: "http://kibana:5601"
