
advertised.listeners=PLAINTEXT://localhost:9092
listeners=PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
transaction.state.log.min.isr=1
controller.quorum.voters=1@localhost:9093
transaction.state.log.replication.factor=1
process.roles=broker,controller
listener.security.protocol.map=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
inter.broker.listener.name=PLAINTEXT
controller.listener.names=CONTROLLER
offsets.topic.replication.factor=1
node.id=1
auto.create.topics.enable=true
min.insync.replicas=1
num.partitions=1
log.dirs=/var/lib/kafka/data
confluent.support.metrics.enable=false